### ISSUE TITLE
Blank page, chart is not drawn

### ISSUE THREAD

**Issue by DrLuiji** [DmitryBaranovskiy/g.raphael#123]
With the new Raphaël (v2.0) all the charts are not drawn. 
The problem is due to an infinite loop.

Temporary workarond:
With the old  Raphaël ver all works fine!

**Comment by mraaroncruz** [comment]
g.raphael.com [demos](http://g.raphaeljs.com/piechart2.html) are also busted from in a similar way  
`Uncaught RangeError: Maximum call stack size exceeded`  
They're linked to raphael v2

**Comment by rzurad** [comment]
This issue will be resolved with the release of g.Raphael 0.5
