### ISSUE TITLE
Demo charts are not showing

### ISSUE THREAD

**Issue by rsertelon** [DmitryBaranovskiy/g.raphael#126]
Hi,

I wanted to see what your charts look like, but they don't show up on the demo website :

http://g.raphaeljs.com/piechart.html
http://g.raphaeljs.com/piechart2.html
http://g.raphaeljs.com/barchart.html
http://g.raphaeljs.com/barchart2.html
http://g.raphaeljs.com/linechart.html
http://g.raphaeljs.com/dotchart.html
http://g.raphaeljs.com/basic.html

I'm using chrome 15 under Ubuntu 11.10 64b.

Cheers ;)

**Comment by rzurad** [comment]
Raphael 2.0 broke compatibility with g.Raphael 0.4.1. The website hasn't been updated with the newest version of g.Raphael 0.5, which fixes that issue. What's in master right now and tagged as v0.5 is working and includes those examples in the `test/` directory, it just needs to be pushed to the website which should happen sometime today or tomorrow.

This issue will be closed once the website has been updated.

**Comment by rsertelon** [comment]
Thanks :)
