### ISSUE TITLE
How to make Pie chart start at 90 degrees

### ISSUE THREAD

**Issue by jasepppp** [DmitryBaranovskiy/g.raphael#22]
Hi,
does anyone know how I could change the pie chart library to start from 90 degrees ?

thanks
jason

**Comment by iwilkes** [comment]
On line 66 of the source g.pie.js:
angle = 90 - mangle;

You can set angle to a fixed value and the chart will always start the left edge of the first slice at that angle:
angle = 90;

I've added a bunch of features like this to my own version, so I'll see about getting them merged back into the official version.

**Comment by DmitryBaranovskiy** [comment]
You can’t

**Comment by jasepppp** [comment]
thanks iwilkes
