### ISSUE TITLE
*Pie Chart won't generate more than 10 sectors*

### ISSUE THREAD

**Issue by gamerdudes** [DmitryBaranovskiy/g.raphael#53]
When I create a pie chart, it doesn't seem capable of creating more than 10 sectors. Please let me know as soon as possible what I'm doing wrong. It draws a piechart, and it does everything perfectly... for ten sectors only. I want to be able to create a dynamic pie chart, where a slice is created for every directorate in my company, and there are 18. Thankyou in advance.

Here is my code, most of which is taken from raphael's site:

// Creates canvas 640 × 480 at 10, 50
var r = Raphael(10, 50, 640, 480);
// Creates pie chart at with center at 320, 200,
// radius 100 and data: [55, 20, 13, 32, 5, 1, 2]
var pie = r.g.piechart(320, 240, 100, [55, 20, 13, 32, 5, 1, 2, 25, 20, 15, 11, 14, 16]);

pie.hover(function () {
this.sector.stop();
this.sector.scale(1.1, 1.1, this.cx, this.cy);
},

function () {
this.sector.animate({scale: [1, 1, this.cx, this.cy]}, 500, "bounce");
})//this is the end of pie.hover

**Comment by DmitryBaranovskiy** [comment]
Not a bug.
Pie chart has a limitation for 10 segments. More than 10 makes chart unreadable.

**Comment by gamerdudes** [comment]
Is there a simple way that I can change this? I would really like to keep Raphael in my project, its a phenomenal tool. It would be a shame to have to switch to a different library over this.

**Comment by aewilsona** [comment]
This is a beautiful work of programming, and I'm thankful for it.
That being said, I was just scratching my head over this same question.
I have a pie chart that represents the contributions of 14 things, 
each of which makes up 6, 7 or 8 percent of the total...
So even though the last 4 segments would each be roughly the same size as each of the other segments, these last 4 all get grouped into Others, which now is over a quarter of the pie in size...   while in cases where there are less things, I see percents as small as 2 get a slice of their own, without making the chart unreadable...  so, I'm with gamerdudes, wondering how to modify the code, but I'm not sure where to get a handle on the piece that needs modified to work so it'll show all 14 things.  I don't want to offend any of them, by grouping them as "Others" over such a small difference...  Thanks in advance for any answer, and thanks again for your great contribution to the available charting tools for the web.

**Comment by gamerdudes** [comment]
You can modify the code to display more, only up to twenty it seems, by changing the "cut" variable ("c" in .min).

**Comment by aewilsona** [comment]
gamerdudes, you rock!  Thank you.  Changing the "c=" in pie.min did the trick.
Then in g.raphael.min adding more color values into the "e" array  and setting the value for "b<"  loop the same as the value for "c=" in pie.min.  Again, great work, Dmitry.  Thanks again to both of you.

**Comment by gamerdudes** [comment]
Thanks, glad I could help.

**Comment by gorodok** [comment]
"Not a bug.
Pie chart has a limitation for 10 segments. More than 10 makes chart unreadable."

I'm sorry, "wat"? =)

**Comment by jayarjo** [comment]
Documentation here: http://g.raphaeljs.com/reference.html#Paper.piechart says: 

<blockquote>
<strong>maxSlices</strong> - a threshold for how many slices should be rendered before collapsing all remaining slices into 1 additional slice (to focus on most important data points). [default 100]
</blockquote>

Note: `default 100`

**Comment by leefsmp** [comment]
Such a pitiful limitation... I overcame that by providing an array of randomly generated colors:
colors.push('#' + Math.floor(Math.random()*16777215).toString(16));
