### ISSUE TITLE
Line chart bug when all y values are 0

### ISSUE THREAD

**Issue by RodolpheGohard** [DmitryBaranovskiy/g.raphael#54]
Hello,

I'm generating charts dynamically with g.raphel , so it happens that all y-values are. In this case, g.raphel throw an exepction:

pathArray[0] is undefined
[Break on this error] if (pathArray[0][0] == "M") { 

I explored the code, And found the reason, a division by 0 on g.line.js, around line 44:

```
    kx = (width - gutter * 2) / (maxx - minx),
    ky = (height - gutter * 2) / (maxy - miny);
```

DO NOT DIVIDE BY ZERO EVER

and there's how i fixed it:

```
    kx = (width - gutter * 2) / ((maxx==minx)?1:maxx-minx),
    ky = (height - gutter * 2) / ((maxy==miny)?1:maxy-miny),
```

**Comment by DmitryBaranovskiy** [comment]
fixed.
