### ISSUE TITLE
PieChart values.sort 

### ISSUE THREAD

**Issue by Evildonald** [DmitryBaranovskiy/g.raphael#56]
I'm not sure if this is intentional, but I found that no matter how I ordered my values, that the highest value would be first in the series.

Going through the piechart.js code I found that if I changed:

```
    values.sort(function(a, b)
    {
        return b.value - a.value; //sorted by value
    });
```

TO

```
    values.sort(function(a, b)
    {
        return b.order - a.order; //sorted by order
    });
```

then the values displayed in the chart according to order and not value.

**Comment by DmitryBaranovskiy** [comment]
This is intentional.

**Comment by Evildonald** [comment]
Why do you even have an order field then?

You might want to consider giving users an option to pick this.  It goes against how nearly every other charting system operates.  
It took me about 45 minutes to work out why my values i specifically were adding in a certain order were being rendered in the opposite order I was indexing them in.

Either remove the order field (which currently does nothing), or give users the option to pick please.

thanks!
